In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("../runs/ml-1m-ordrec-0/test_error_conf-0.csv")

In [8]:
df.describe()

,userId,movieId,rating,timestamp,negative_sampled,r_pred,conf_pred,rank_scores,abs_error
count,380179.000000,380179.000000,380179.000000,1.288990e+05,380179.000000,380179.0,380179.000000,3.801790e+05,380179.000000
mean,3041.945381,1689.140531,1.839307,9.777964e+08,0.660952,5.0,0.952542,1.000000e+00,3.160693
std,1744.540439,979.019336,1.342077,1.835107e+07,0.473387,0.0,0.002085,3.440715e-08,1.342077
min,1.000000,0.000000,1.000000,9.567061e+08,0.000000,5.0,0.944274,9.999999e-01,0.000000
25%,1500.000000,861.000000,1.000000,9.658400e+08,0.000000,5.0,0.951134,1.000000e+00,2.000000
50%,3094.000000,1680.000000,1.000000,9.746962e+08,1.000000,5.0,0.952593,1.000000e+00,4.000000
75%,4533.000000,2535.000000,3.000000,9.781444e+08,1.000000,5.0,0.954004,1.000000e+00,4.000000
max,6039.000000,3415.000000,5.000000,1.046455e+09,1.000000,5.0,0.959789,1.000000e+00,4.000000